app/routes/about/routes.py
from flask import (Blueprint, render_template)


# Flask Blueprint
about_page = Blueprint("about", __name__)


@about_page.route("/about", methods=["GET", "POST"])
def about():
    """
    View to open the about page
    """

    return render_template("landpage.html")

app/routes/likes/routes.py
from flask import (Blueprint, session, jsonify,
                   redirect, url_for)
from bson.objectid import ObjectId
from app.utils import (trips_collection, Trip)


# Flask Blueprint
likes_func = Blueprint("likes", __name__)


@ likes_func.route('/likes/<trip_id>', methods=["GET", "POST"])
def likes(trip_id):
    """
    Count likes
    """

    try:
        # Instance of Trip Class
        trip_func = Trip(None, None, None,
                         None, None, None,
                         None, None, None,
                         None)

        current_user = session['user']
        trip = trips_collection.find_one({'_id': ObjectId(trip_id)})
        likes = trip['trip_likes']

        # Handle likes counting
        like_icon, count_likes = trip_func.like(current_user,
                                                trip_id,
                                                trip,
                                                likes)

        return jsonify({'result': 'success',
                        'current_user': current_user,
                        'trip_id': trip_id,
                        'like_icon': like_icon,
                        'count_likes': count_likes})
    except KeyError:
        """
        Catch KeyError in case there is no session called 'user'
        and redirect to the feed page
        """

        return redirect(url_for('main.feed'))

app/routes/login/routes.py
from flask import (Blueprint, session,
                   request, flash,
                   redirect, url_for)
from app.utils import User


# Flask Blueprint
login_func = Blueprint("login", __name__)


@login_func.route("/login", methods=["GET", "POST"])
def login():
    """
    View to handle the login form modal
    """

    if request.method == "POST":

        # Instance of User Class
        user_func = User(None,
                         None,
                         request.form.get("emailL"),
                         request.form.get("passwordL"))

        # Return if the user exists and if the password matches
        existing_user, password, user = user_func.login()

        # Check if the user exists and if the password matches
        if existing_user:
            if password:

                # Put the user into 'session' cookie
                session["user"] = str(user["_id"])

                # redirect to user's profile
                flash("Welcome, {}".format(
                    user["fname"].capitalize()))
                return redirect(url_for("profile.profile"))

            else:
                # Invalid password
                flash("Incorrect email and/or password")
                return redirect(request.referrer)

        else:
            # Username doesn't exist
            flash("Incorrect email and/or password")
            return redirect(request.referrer)

    # If the user does not exist or the password does not match,
    # redirect to previous page
    return redirect(request.referrer)

app/routes/trip/routes.py
from flask import (Blueprint, render_template,
                   session)
from bson.objectid import ObjectId
from app.config import Config
from app.utils import (users_collections, trips_collection,
                       User, Trip)


# Flask Blueprint
trip_pag = Blueprint("trip", __name__)


@trip_pag.route('/trip/<trip_id>', methods=["GET", "POST"])
def trip(trip_id):
    """
    View to open the trip post
    """

    # Instance of Trip Class
    trip_func = Trip(None, None, None,
                     None, None, None,
                     None, None, None,
                     None)

    trip = trips_collection.find_one({'_id': ObjectId(trip_id)})
    resources = trip_func.folder_resources(trip_id)

    num_photos = trip_func.get_no_pictures(trip['user'], trip['_id'])
    map = Config.MAP_KEY

    if session.get('user'):
        current_user_id = session['user']
        current_user = users_collections.find_one(
            {'_id': ObjectId(current_user_id)})
        notifications = current_user['notifications']
    else:
        notifications = None

    # Instance of User Class
    user_func = User(None, None, None, None)

    return render_template('trip.html',
                           trip=trip,
                           profile_pic=user_func.get_profile_pic,
                           resources=resources,
                           img_url=trip_func.img_url,
                           map=map,
                           num_photos=num_photos,
                           notifications=notifications)

app/templates/partials/_login_modal.html
<!-- Login modal -->
<div class="row no-gutters">
    <div class="col-12">
        <div id="login" class="modal loginModal">

            <!-- Modal content -->
            <div class="modal-content">
                <div class="row no-gutters">
                    <div class="col-2 ml-auto">
                        <span class="close closeLogin">&times;</span>
                    </div>

                    <!-- form -->
                    <div class="col-12">
                        <!-- Login Form from bootstrap -->
                        <form id="loginForm" method="POST" action="{{ url_for('login.login') }}">
                            <fieldset class="content-alignment">
                                <div class="card loginCard">

                                    <h3 class="text-center">Login</h3>

                                    <!-- Email Field -->
                                    <div class="row no-gutters content-alignment">
                                        <div class="col-12 col-md-8">
                                            <label for="email">Email</label>
                                            <input type="email" id="emailL" name="emailL" class="form-control"
                                                placeholder="Email" required>
                                        </div>
                                    </div>

                                    <!-- Password field -->
                                    <div class="row no-gutters content-alignment">
                                        <div class="col-12 col-md-8">
                                            <label for="password">Password</label>
                                            <input type="password" id="passwordL" name="passwordL" minlength="6"
                                                maxlength="15" pattern="^[a-zA-Z0-9]{6,15}$" class="form-control"
                                                placeholder="Password" required>
                                        </div>
                                    </div>

                                    <!-- LogIn Button -->
                                    <div class="row no-gutters text-center">
                                        <div class="col-12">
                                            <button type="submit" class="btn btn-primary btn-lg registerBtn">Log
                                                In</button>
                                        </div>
                                    </div>
                                </div>
                            </fieldset>
                        </form>
                    </div>

                </div>
            </div>

        </div>
    </div>
</div>

app/templates/partials/_navbar.html
<nav class="navbar navbar-expand-lg navbar-light">
    {% if not session.user %}
    <a class="navbar-brand" href="{{ url_for('main.feed') }}" aria-label="Go to feed page"><img id="logo"
            src="{{ url_for('static', filename='images/navbar/borderless_logo.png') }}" alt="Borderless Logo"></a>
    {% else %}
    <a class="navbar-brand" href="{{ url_for('main.feed') }}" aria-label="Go to feed page"><img id="logo"
            src="{{ url_for('static', filename='images/navbar/logo_session.png') }}" alt="Borderless Logo"></a>
    {% endif %}

    <!-- side nav button for small and medium screens -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span><i class="fas fa-bars"></i></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <!-- Navbar and side items -->
        <ul class="navbar-nav ml-auto">
            {% if session.user %}
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('main.feed') }}" aria-label="Go to feed page"><i class="fas fa-globe-americas"></i></a>
            </li>
            {% if notifications|length != 0 %}
            <li class="nav-item">
                <div class="dropdown dropleft">
                    <a href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true"
                        aria-expanded="false" aria-label="Notification">
                        <i class="fas fa-bell"></i>
                    </a>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        <div class="dropdown-item">
                            {% for ntf in notifications %}
                            <!-- Notification container -->
                            <div id="ntf_{{ ntf._id }}" class="row no-gutters notification">
                                <div class="col-12 notifContainer">
                                    <div class="row no-gutters">
                                        <div class="col-12 requestText">
                                            <p><a
                                                    href="{{ url_for('public_profile.public_profile', trip_user=ntf._id) }}" aria-label="Follow requester profile">{{
                                                    ntf.name }}</a> sent a follow request</p>
                                        </div>
                                        <div class="col-6 content-alignment requestBtn">
                                            <a class="btn btn-danger btn-sm" aria-label="Refuse follow request">Refuse</a>
                                        </div>
                                        <div class="col-6 content-alignment requestBtn">
                                            <a id="accept_btn_{{ ntf._id }}" class="btn btn-primary btn-sm accept_btn"
                                                data-id="{{ ntf._id }}"
                                                href="{{ url_for('follow_request.follow_request', user_id=ntf._id) }}" aria-label="Accept follow request">Accept</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </li>
            {% else %}
            <li class="nav-item">
                <div class="dropdown dropleft">
                    <a href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true"
                        aria-expanded="false" aria-label="Notifications">
                        <i class="far fa-bell"></i>
                    </a>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        <div class="dropdown-item">

                            <!-- Notification container -->
                            <div class="row no-gutters notification">
                                <div class="col-12">
                                    <p class="text-center">No notifications at the moment</p>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </li>
            {% endif %}
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('about.about') }}" aria-label="Go to about page">About</a>
            </li>
            <li class="nav-item">
                <a class="nav-link signUpBtn" aria-label="Open sign up modal form">SignUp</a>
            </li>
            <li class="nav-item">
                <a id="loginBtn" class="nav-link" aria-label="Open Log in modal form">Login</a>
            </li>
            {% endif %}
        </ul>
        {% if session.user %}
        <div>
            <div class="dropdown dropleft">
                <a href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true"
                    aria-expanded="false" aria-label="Profile menu">
                    <img id="profileLinkPic" src="{{ profile_pic(session.user) }}" alt="Profile Link Photo">
                </a>

                <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                    <a class="dropdown-item" href="{{ url_for('profile.profile') }}" aria-label="Go to profile page"><i class="fas fa-user"></i>
                        Profile</a>
                    <a class="dropdown-item" href="{{ url_for('edit_profile.edit_profile') }}" aria-label="Go to edit profile page"><i
                            class="fas fa-user-edit"></i> Edit Profile</a>
                    <a class="dropdown-item" href="{{ url_for('logout.logout') }}" aria-label="Log out"><i class="fas fa-sign-out-alt"></i>
                        Log Out</a>
                </div>
            </div>
        </div>
        {% endif %}
    </div>
</nav>

app/templates/partials/_pagination_bottom.html
<!-- Pagination links bottom -->
<div class="col-12 pagination paginationBottom content-alignment">
    {% if page != 1 %}
    <a class="page-link" href="{{ prev_pag }}" aria-label="Previous page">&laquo;</a>
    {% endif %}
    {% set count = namespace(value=0) %}
    {% for pageNum in range(num_pages) %}
    <a class="pageLink page-link" data-page='{{ page }}'
        href="{{ pag_link(pag_name, sec_arg, limit, count.value, loop.index) }}" aria-label="Page {{ page }}">{{loop.index }}</a>
    {% set count.value = count.value + offset_sum %}
    {% endfor %}
    {% if num_pages != page %}
    <a class="page-link" href="{{ next_pag }}" aria-label="Next page">&raquo;</a>
    {% endif %}
</div>

app/templates/partials/_pagination_top.html
<!-- Pagination links top -->
<div class="col-12 pagination paginationTop content-alignment">

    <!-- Previous page link -->
    {% if page != 1 %}
    <a class="page-link" href="{{ prev_pag }}" aria-label="Previous page">&laquo;</a>
    {% endif %}

    <!-- Page links -->
    {% set count = namespace(value=0) %}
    {% for pageNum in range(num_pages) %}
    <a class="pageLink page-link" data-page='{{ page }}'
        href="{{ pag_link(pag_name, sec_arg, limit, count.value, loop.index) }}" aria-label="Page {{ page }}">{{loop.index }}</a>
    {% set count.value = count.value + offset_sum %}
    {% endfor %}

    <!-- Next page link -->
    {% if num_pages != page %}
    <a class="page-link" href="{{ next_pag }}" aria-label="Next Page">&raquo;</a>
    {% endif %}
</div>

app/templates/partials/_post.html
<!-- Trip Post -->
<div class="col-11 tripPostLink">

    <!-- Post background -->
    <img class="postBackground img-centered" src="{{ bg_post_url(trip.user, trip._id) }}" alt="Trip post background">

    <div class="row no-gutters">
        {% if trip.user == current_user_id or path == (request.path)|string %}

        <!-- Post author picture -->
        <div class="col-8 col-md-10">
            <img class="postLinkProfilePic" src="{{ user_photo(trip.user) }}" alt="Post author profile photo">
        </div>
        {% else %}
        <div class="col-10">

            <!-- Post author picture link -->
            <a href="{{ url_for('public_profile.public_profile', trip_user=trip.user) }}"
                aria-label="Go to post author profile"><img class="postLinkProfilePic shadowEffect"
                    src="{{ user_photo(trip.user) }}" alt="Post author profile photo"></a>
        </div>
        {% endif %}
        {% if trip.user == current_user_id %}
        <!-- Delete trip Button -->
        <div class="col-2 col-md-1 deleteTrip">
            <a id="deleteTripBtn_{{ trip._id }}" class="deletePost" data-id="{{ trip._id }}"
                aria-label="Delete trip icon"><i class="fas fa-trash-alt shakeEffect"></i></a>
        </div>

        <!-- Edit trip button -->
        <div class="col-2 col-md-1 editTrip">
            <a href="{{ url_for('edit_trip.edit_trip', trip_id=trip._id) }}" aria-label="Edit trip icon"><i
                    class="fas fa-pencil-alt shakeEffect"></i></a>
        </div>
        {% endif %}

    </div>

    <!-- Link to open the trip -->
    <div class="row no-gutters postNameDate">
        <div class="col-12 text-center">
            <a href="{{ url_for('trip.trip', trip_id=trip._id) }}" aria-label="Go to trip view">
                <h1 class="shadowEffect">{{ trip['trip_name']|title }}</h1>
                <div>
                    <span id="startDate_{{ trip._id }}">{{ trip['trip_startdate'].strftime('%Y-%m-%d')
                        }}</span>
                    <span>to</span> <span id="endDate_{{ trip._id }}">{{
                        trip['trip_end_date'].strftime('%Y-%m-%d')
                        }}</span>
                </div>
            </a>
        </div>
    </div>

    <div class="row no-gutters postStatistic">
        <div class="col-12 text-center">
            <div>
                <span class="totalDays" id="totalDays_{{ trip._id }}"><i class="fas fa-calendar-alt"></i> <span>{{
                        ((trip['trip_end_date'] - trip['trip_startdate']).days)|string + '
                        days'
                        }}</span></span>
                <span id="totalPhotos_{{ trip._id }}"><i class="fas fa-images"></i> <span>{{
                        no_files(trip.user, trip._id) }}</span></span>
            </div>
        </div>
    </div>

    <!-- The delete trip confirmation modal -->
    {% include "partials/_rm_trip_modal.html" %}

    <!-- Likes Button -->
    {% if session.user %}
    <div class="row no-gutters postLikes">
        <div class="col-12 text-center">
            <a href="{{ url_for('likes.likes', trip_id=trip._id) }}" class="like" data-trip="{{ trip._id }}"
                aria-label="Like button">
                <i id="{{ 'like_icon_%s' % trip._id }}" class="fas fa-heart shakeEffect"></i>
            </a>
            <span name="like_count" id="{{'like_count_%s' % trip._id}}">{{
                trip.trip_likes|length }}</span>
        </div>
    </div>
    {% endif %}

</div>

app/templates/partials/_rm_trip_modal.html
<!-- The delete trip confirmation modal -->
<div class="row no-gutters">
    <div class="col-12">
        <div id="deleteTripModal_{{ trip._id }}" class="modal deleteTripModal">

            <!-- Modal content -->
            <div class="modal-content">
                <div class="row no-gutters">
                    <div class="col-2 ml-auto">
                        <span class="close closeDeleteConfirm">&times;</span>
                    </div>

                    <!-- Confirmation message -->
                    <div class="col-12">
                        <div class="row no-gutters">
                            <div class="col-12">
                                <h2 class="text-center">You are going to delete this
                                    trip! Are you sure?</h2>
                            </div>
                        </div>
                        <hr>
                        <div class="row no-gutters content-alignment deleteBtnModal">
                            <div class="col-2 content-alignment">
                                <a class="btn btn-primary closeDeleteConfirm" aria-label="Close delete trip confirmation">Cancel</a>
                            </div>
                            <div class="col-2 content-alignment">
                                <a class="btn btn-danger"
                                    href="{{ url_for('delete_trip.delete_trip', trip_id=trip._id) }}" aria-label="delete trip confirm Button">Delete</a>
                            </div>
                        </div>
                    </div>

                </div>
            </div>

        </div>
    </div>
</div>

app/templates/partials/_searchbar.html
<!-- Search Bar -->
<form {% if path !=(request.path)|string %} action="{{ url_for(query_page) }}" {% else %}
    action="{{ url_for(query_page, trip_user=user._id) }}" {% endif %} method="POST"
    class="content-alignment profileSearchForm">
    <div class="row no-gutters">

        <!-- Search Bar -->
        <div class="col-11 col-md-6 col-lg-6 col-xl-6">
            <input id="query" name="query" class="searchInput form-control mr-sm-2" type="search" minlength="3"
                placeholder="Search" aria-label="Search" required>
        </div>

        <!-- Search Reset Button -->
        <div class="col-2 col-md-2 col-lg-2 col-xl-2 searchProfileButtons">
            <a {% if path !=(request.path)|string %} href="{{ url_for(query_page) }}" {% else %}
                href="{{ url_for('public_profile.public_profile', trip_user=user._id) }}" {% endif %}
                class="btn btn-outline-danger my-sm-0" aria-label="Reset search query">Reset</a>
        </div>

        <!-- Search Button -->
        <div class="col-2 col-md-2 col-lg-2 col-xl-2 searchProfileButtons resetSearchProfile">
            <button type="submit" class="btn btn-outline-primary my-sm-0">Search</button>
        </div>
    </div>
</form>

app/templates/partials/_signup_modal.html
<!-- signUp modal -->
<div class="row no-gutters">
    <div class="col-12">
        <div id="signUp" class="modal signUpModal">

            <!-- Modal content -->
            <div class="modal-content">
                <div class="row no-gutters">
                    <div class="col-2 ml-auto">
                        <span class="close closeSignUp">&times;</span>
                    </div>

                    <!-- form -->
                    <div class="col-12">
                        <form method="POST" action="{{ url_for('signup.signup') }}">
                            <fieldset class="content-alignment">
                                <div class="card signUpCard">

                                    <h3 class="text-center">Sign Up</h3>

                                    <!-- First Name Field -->
                                    <div class="row no-gutters content-alignment">
                                        <div class="col-12 col-md-8">
                                            <label for="fname">First Name</label>
                                            <input type="text" id="fname" name="fname" minlength="2" maxlength="15"
                                                pattern="^[a-zA-Z0-9]{2,15}$" class="form-control"
                                                placeholder="First name" required>
                                        </div>
                                    </div>

                                    <!-- Last Name Field -->
                                    <div class="row no-gutters content-alignment">
                                        <div class="col-12 col-md-8">
                                            <label for="lname">Last Name</label>
                                            <input type="text" id="lname" name="lname" minlength="2" maxlength="15"
                                                pattern="^[a-zA-Z0-9]{2,15}$" class="form-control"
                                                placeholder="Last name" required>
                                        </div>
                                    </div>

                                    <!-- Email Field -->
                                    <div class="row no-gutters content-alignment">
                                        <div class="col-12 col-md-8">
                                            <label for="email">Email</label>
                                            <input type="email" id="email" name="email" class="form-control"
                                                placeholder="Email"
                                                required>
                                        </div>
                                    </div>

                                    <!-- Password Field -->
                                    <div class="row no-gutters content-alignment">
                                        <div class="col-12 col-md-8">
                                            <label for="password">Password</label>
                                            <input type="password" id="password" name="password" minlength="6"
                                                maxlength="15" pattern="^[a-zA-Z0-9]{6,15}$" class="form-control"
                                                placeholder="Password" required>
                                        </div>
                                    </div>

                                    <!-- Repeat Password Field -->
                                    <div class="row no-gutters content-alignment">
                                        <div class="col-12 col-md-8">
                                            <label for="Rpassword">Confirm Password</label>
                                            <input type="password" id="Rpassword" name="Rpassword" minlength="6"
                                                maxlength="15" pattern="^[a-zA-Z0-9]{6,15}$" class="form-control"
                                                placeholder="Password" required>
                                        </div>
                                    </div>

                                    <!-- Register Button -->
                                    <div class="row no-gutters text-center">
                                        <div class="col-12">
                                            <button type="submit" class="btn btn-primary btn-lg registerBtn"
                                                disabled>Register</button>
                                        </div>
                                    </div>
                                </div>
                            </fieldset>
                        </form>
                    </div>

                </div>
            </div>

        </div>
    </div>
</div>