app/routes/about/routes.py
from flask import (Blueprint, render_template)


# Flask Blueprint
about_page = Blueprint("about", __name__)


@about_page.route("/about", methods=["GET", "POST"])
def about():
    """
    View to open the about page
    """

    return render_template("landpage.html")

app/routes/delete_img/routes.py
from flask import (Blueprint, jsonify,
                   redirect, url_for)
from app.utils import Trip


# Flask Blueprint
delete_img_func = Blueprint("delete_img", __name__)


@delete_img_func.route('/delete_img/<trip_id>/<filename>',
                       methods=["GET", "POST"])
def delete_img(trip_id, filename):
    """
    Delete one image from cloud platform
    """

    try:
        # Instance of Trip Class
        trip_func = Trip(None, None, None,
                         None, None, None,
                         None, None, None,
                         None)

        # Handle image deletion
        trip_func.delete_img(trip_id, filename)

        return jsonify({'result': 'success'})
    except KeyError:
        """
        Catch KeyError in case there is no session called 'user'
        and redirect to the feed page
        """

        return redirect(url_for('main.feed'))

app/routes/edit_profile/routes.py
from flask import (Blueprint, render_template,
                   session, request, flash,
                   redirect, url_for)
from bson.objectid import ObjectId
from app.utils import (users_collections, User)


# Flask Blueprint
edit_profile_page = Blueprint("edit_profile", __name__)


@edit_profile_page.route('/edit_profile', methods=["POST", "GET"])
def edit_profile():
    """
    View to edit profile
    """

    try:
        current_user = users_collections.find_one(
            {'_id': ObjectId(session['user'])})

        if request.method == 'POST':

            # Instance of User Class (POST request)
            user_func = User(request.form.get('fname'),
                             request.form.get('lname'),
                             None, None)

            # Update profile and cover pictures in cloud platform
            profile_photo = request.files['profile_photo']
            if profile_photo.filename != "":
                user_func.update_profile_pic(profile_photo)

            cover_photo = request.files['cover_photo']
            if cover_photo.filename != "":
                user_func.update_cover_pic(cover_photo)

            # Update name in DB
            user_func.update_name()

            # Redirect to profile page after update
            flash('Profile Updated')
            return redirect(url_for('profile.profile'))

        # Instance of User Class (GET request)
        user_func = User(None, None, None, None)

        # Get current user's notifications
        notifications = current_user['notifications']
    except KeyError:
        """
        Catch KeyError in case there is no session called 'user'
        and redirect to the feed page
        """

        return redirect(url_for("main.feed"))

    return render_template("edit_profile.html",
                           profile_pic=user_func.get_profile_pic,
                           cover_pic=user_func.get_cover_pic,
                           current_user=current_user,
                           notifications=notifications)

app/routes/edit_trip/routes.py
from flask import (Blueprint, render_template,
                   session, request, flash,
                   redirect, url_for)
from bson.objectid import ObjectId
import datetime as dt
import cloudinary
import cloudinary.uploader
import cloudinary.api
from app.utils import (users_collections, trips_collection,
                       User, Trip)
from app.config import Config


# Configure Cloudinary API
cloudinary.config(
    cloud_name=Config.CLOUD_NAME,
    api_key=Config.API_KEY,
    api_secret=Config.API_SECRET,
    secure=True
)


# Flask Blueprint
edit_trip_pag = Blueprint("edit_trip", __name__)


@edit_trip_pag.route('/edit_trip/<trip_id>', methods=['GET', 'POST'])
def edit_trip(trip_id):
    """
    View to edit a trip
    """

    try:
        current_trip = trips_collection.find_one({'_id': ObjectId(trip_id)})
        current_catg = current_trip['trip_category'].lower()
        current_name = current_trip['trip_name'].lower()
        current_user = session['user']
        search_exp = (current_trip['trip_name']).replace(" ", " AND ")
        trip_path = cloudinary.Search().expression(search_exp).execute()
        resources = trip_path['resources']
        ids = []

        if len(resources) > 0:
            for res in range(len(resources)):
                last_file = resources[res]['filename']
                last_file_id = int(last_file[-1])
                ids.append(last_file_id)

        # Instance of Trip Class
        trip_func = Trip(None, None, None,
                         None, None, None,
                         None, None, None,
                         None)

        if request.method == "POST":
            # Catch data from form into variables
            trip_category = request.form.get("trip_category").lower()
            trip_name = request.form.get("trip_name").lower()
            trip_place_name = request.form.get("trip_place_name")
            trip_country = request.form.get("trip_country")
            trip_description = request.form.get("trip_description")
            trip_startdate = dt.datetime.strptime(
                request.form.get("trip_startdate"), '%Y-%m-%d')
            trip_end_date = dt.datetime.strptime(
                request.form.get("trip_end_date"), '%Y-%m-%d')
            trip_photos = request.files.getlist('trip_photos')
            trip_privacy = request.form.get("trip_privacy")

            # Instance of Trip Class for POST request method
            trip_func = Trip(current_trip['user'],
                             None,
                             trip_category,
                             trip_name,
                             trip_place_name,
                             trip_country,
                             trip_description,
                             trip_startdate,
                             trip_end_date,
                             trip_privacy)

            # Handle trip update
            trip_func.edit_trip(current_catg,
                                current_name,
                                resources,
                                current_trip,
                                trip_photos,
                                ids)

            flash('Trip Updated')
            return redirect(url_for('profile.profile'))

        # Current user notifications
        current_user_id = session['user']
        current_user = users_collections.find_one(
            {'_id': ObjectId(current_user_id)})
        notifications = current_user['notifications']

        # Instance of User Class
        user_func = User(None, None, None, None)
    except KeyError:
        """
        Catch KeyError in case there is no session called 'user'
        and redirect to the feed page
        """

        return redirect(url_for('main.feed'))

    return render_template('edit_trip.html',
                           profile_pic=user_func.get_profile_pic,
                           current_user=current_user,
                           current_trip=current_trip,
                           countries=trip_func.countries(),
                           trip_path=trip_path,
                           img_url=trip_func.img_url,
                           notifications=notifications)

app/routes/follow_request/routes.py
from flask import (Blueprint, session,
                   jsonify, redirect,
                   url_for)
from bson.objectid import ObjectId
from app.utils import (users_collections, User)


# Flask Blueprint
follow_request_func = Blueprint("follow_request", __name__)


@follow_request_func.route("/follow_request/<user_id>",
                           methods=["POST", "GET"])
def follow_request(user_id):
    """
    Follow request
    """

    try:
        # Instance of User Class
        user_func = User(None, None, None, None)

        # Current user
        current_user = users_collections.find_one(
            {'_id': ObjectId(session['user'])})

        # Current user's followers
        rqt_current_user = current_user['followers']

        # Any user who was requested to be friend
        user = users_collections.find_one(
            {'_id': ObjectId(user_id)})

        # Handle follow request
        flwn_count = user_func.follow_request(current_user,
                                              rqt_current_user,
                                              user,
                                              user_id)

        return jsonify({
            'result': 'success',
            'user': user_id,
            'flwn_count': flwn_count
        })
    except KeyError:
        """
        Catch KeyError in case there is no session called 'user'
        and redirect to the feed page
        """

        return redirect(url_for('main.feed'))

app/routes/notification/routes.py
from flask import (Blueprint, session,
                   jsonify)
from bson.objectid import ObjectId
from app.utils import (users_collections, User)


# Flask Blueprint
notification_func = Blueprint("notification", __name__)


@notification_func.route("/notification/<user_id>",
                         methods=["POST", "GET"])
def notification(user_id):
    """
    Notifications
    """

    # Instance of User Class
    user_func = User(None, None, None, None)

    # Current user
    current_user = users_collections.find_one(
        {'_id': ObjectId(session['user'])})

    # Any user who was requested to be friend
    user = users_collections.find_one(
        {'_id': ObjectId(user_id)})
    # User notifications
    ntf_user = user['notifications']

    # Handle notification functionality
    user_func.notification(current_user, user, ntf_user, user_id)

    return jsonify({'result': 'success'})

app/routes/public_profile/routes.py
from flask import (Blueprint, render_template,
                   session, request)
from bson.objectid import ObjectId
from app.utils import (users_collections, trips_collection,
                       Pagination, User, Trip)


# Flask Blueprint
public_profile_pag = Blueprint("public_profile", __name__)


@ public_profile_pag.route('/public_profile/<trip_user>',
                           methods=["GET", "POST"])
def public_profile(trip_user):
    """
    Public profile view
    """

    # Instance of User Class
    user_func = User(None, None, None, None)

    # Instance of Trip Class
    trip_func = Trip(None, None, None,
                     None, None, None,
                     None, None, None,
                     None)

    # Any user data
    user = users_collections.find_one({'_id': ObjectId(trip_user)})

    # Pagination
    db = trips_collection
    db_field = 'user'
    db_field_data = ObjectId(trip_user)
    sort_data = 'trip_startdate'
    sort_direction = -1
    pag_name = "public_profile"
    sec_arg = trip_user
    offset_sum = 5
    query_page = 'public_profile.public_profile'
    path = "/public_profile/%s" % trip_user

    if request.method == "POST":
        if request.args:
            offset = int(request.args['offset'])
            limit = int(request.args['limit'])
            page = int(request.args['page'])
            query = request.args['query']

            pprofile_pag = Pagination(db,
                                      db_field,
                                      db_field_data,
                                      sort_data,
                                      sort_direction,
                                      offset,
                                      limit,
                                      query)
        else:
            query = request.form.get('query')

            offset = 0
            limit = 5
            page = 1

            pprofile_pag = Pagination(db,
                                      db_field,
                                      db_field_data,
                                      sort_data,
                                      sort_direction,
                                      offset,
                                      limit,
                                      query)

        trips_pag = pprofile_pag.pag_data()
        num_pages = pprofile_pag.num_pages()
        prev_pag = pprofile_pag.pag_link('public_profile',
                                         trip_user,
                                         limit,
                                         (offset - limit),
                                         (page - 1))
        next_pag = pprofile_pag.pag_link('public_profile',
                                         trip_user,
                                         limit,
                                         (offset + limit),
                                         (page + 1))
    else:
        if request.args:
            offset = int(request.args['offset'])
            limit = int(request.args['limit'])
            page = int(request.args['page'])

            if 'query' in request.args:
                query = request.args['query']
            else:
                query = None

            pprofile_pag = Pagination(db,
                                      db_field,
                                      db_field_data,
                                      sort_data,
                                      sort_direction,
                                      offset,
                                      limit,
                                      query)
        else:
            offset = 0
            limit = 5
            page = 1
            query = None

            pprofile_pag = Pagination(db,
                                      db_field,
                                      db_field_data,
                                      sort_data,
                                      sort_direction,
                                      offset,
                                      limit,
                                      query)

        trips_pag = pprofile_pag.pag_data()
        num_pages = pprofile_pag.num_pages()
        prev_pag = pprofile_pag.pag_link('public_profile',
                                         trip_user,
                                         limit,
                                         (offset - limit),
                                         (page - 1))
        next_pag = pprofile_pag.pag_link('public_profile',
                                         trip_user,
                                         limit,
                                         (offset + limit),
                                         (page + 1))

    # Get notifications for the current user
    if session.get('user'):
        current_user_id = session['user']
        current_user = users_collections.find_one(
            {'_id': ObjectId(current_user_id)})
        notifications = current_user['notifications']
        current_user_followers = current_user['followers']
    else:
        notifications = None
        current_user_followers = None

    # Public profile user
    user_ntf = user['notifications']
    user_followers = user['followers']
    user_following = user['following']

    ntf_id = []
    for ntf in range(len(user_ntf)):
        ntf_id.append(user_ntf[ntf]['_id'])

    # Statistics
    ctr, plc, days, long, ph = trip_func.statistics(trip_user)

    return render_template('public_profile.html',
                           profile_pic=user_func.get_profile_pic,
                           user_photo=trip_func.user_post_photo,
                           cover_pic=user_func.get_cover_pic,
                           bg_post_url=trip_func.get_BGPost_pic,
                           no_files=trip_func.get_no_pictures,
                           query_page=query_page,
                           path=path,
                           trips=trips_pag,
                           user=user,
                           full_name=user_func.get_full_name,
                           num_pages=num_pages,
                           limit=limit,
                           offset=offset,
                           page=page,
                           prev_pag=prev_pag,
                           next_pag=next_pag,
                           pag_link=pprofile_pag.pag_link,
                           pag_name=pag_name,
                           sec_arg=sec_arg,
                           offset_sum=offset_sum,
                           notifications=notifications,
                           ntf_id=ntf_id,
                           user_followers=user_followers,
                           user_following=user_following,
                           current_user_followers=current_user_followers,
                           num_coun=ctr,
                           num_plc=plc,
                           total_days=days,
                           long_day=long,
                           total_photos=ph)

app/templates/edit_profile.html
{% extends 'base.html' %}
{% block content %}
<div class="content-wrapper">

    <form method="POST" action="{{ url_for('edit_profile.edit_profile') }}" enctype="multipart/form-data">
        <fieldset class="content-alignment">
            <div class="card editCard">
                <div class="text-center">
                    <legend>Edit Profile</legend>
                </div>

                <!-- First Name Field -->
                <div class="row no-gutters content-alignment">
                    <div class="col-8">
                        <label for="fname">First Name</label>
                        <input type="text" id="fname" name="fname" minlength="3" maxlength="15"
                            pattern="^[a-zA-Z0-9]{3,15}$" class="form-control"
                            value="{{ current_user.fname|title }}" required>
                    </div>
                </div>

                <!-- Last Name Field -->
                <div class="row no-gutters content-alignment">
                    <div class="col-8">
                        <label for="lname">Last Name</label>
                        <input type="text" id="lname" name="lname" minlength="5" maxlength="15"
                            pattern="^[a-zA-Z0-9]{5,15}$" class="form-control"
                            value="{{ current_user.lname|title }}" required>
                    </div>
                </div>

                <!-- Profile Photo -->
                <div class="row no-gutters content-alignment newProfile">
                    <div class="col-12 col-lg-2 col-xl-2 content-alignment">
                        <img class="currentProfilePic" src="{{ profile_pic(session.user) }}" alt="Current avatar picture">
                    </div>
                    <div class="col-8 col-lg-6 col-xl-6">
                        <label for="profile_photo" class="form-label">New Profile Picture</label>
                        <input class="form-control" type="file" id="profile_photo" name="profile_photo"
                            class="newProfileCover" accept="image/jpg, image/jpeg, image/png" />
                    </div>
                </div>

                <!-- New Cover Picture -->
                <div class="row no-gutters content-alignment newCover">
                    <div class="col-12 col-lg-2 col-xl-2 content-alignment">
                        <img class="currentCoverPic" src="{{ cover_pic(session.user) }}" alt=" current cover picture">
                    </div>
                    <div class="col-8 col-lg-6 col-xl-6">
                        <label for="cover_photo" class="form-label">New Cover Picture</label>
                        <input class="form-control" type="file" id="cover_photo" name="cover_photo"
                            class="newProfileCover" accept="image/jpg, image/jpeg, image/png" />
                    </div>
                </div>

                <!-- Register Button -->
                <div class="row no-gutters text-center">
                    <div class="col-12">
                        <button type="submit" class="btn btn-primary btn-lg registerBtn">Update Profile</button>
                    </div>
                </div>
            </div>
        </fieldset>
    </form>
</div>
{% endblock %}

app/templates/edit_trip.html
{% extends 'base.html' %}
{% block content %}

<div class="content-wrapper">

    <div class="row no-gutters content-alignment">

        <!-- Edit Trip Form -->
        <div class="col-12 col-md-10 col-lg-8 edit_trip_wrapper content-alignment">
            <form method="POST" action="{{ url_for('edit_trip.edit_trip', trip_id=current_trip._id) }}"
                enctype="multipart/form-data" class="editTripForm">

                <legend class="text-center">Edit Trip</legend>

                <!-- Trip Category -->
                <div class="form-row">
                    <div class="col-12">
                        <div class="form-group">
                            <label for="trip_category">Trip Category</label>
                            <select class="form-control" id="trip_category" name="trip_category" required>
                                <option selected hidden>{{ current_trip.trip_category }}</option>
                                <option>Travel</option>
                                <option>Vacation</option>
                                <option>Short Trip</option>
                            </select>
                        </div>
                    </div>
                </div>

                <!-- Trip Name -->
                <div class="form-row newTripForm">
                    <div class="col">
                        <div class="form-group">
                            <label for="trip_name">Trip Name</label>
                            <input type="text" class="form-control" id="trip_name" name="trip_name" minlength="5"
                                maxlength="30" pattern="[a-zA-Z\s]+" placeholder="Holidays in Rome"
                                value="{{ current_trip['trip_name']|title }}" required>
                        </div>
                    </div>
                </div>

                <!-- Place Name  and Country -->
                <div class="form-row">
                    <div class="col-12 col-md-6 col-lg-6 col-xl-6">
                        <div class="form-group">
                            <label for="trip_place_name">Place Name</label>
                            <input type="text" class="form-control" id="trip_place_name" name="trip_place_name"
                                minlength="5" maxlength="15" placeholder="Rome"
                                value="{{ current_trip.trip_place_name }}" required>
                        </div>
                    </div>
                    <div class="col-12 col-md-6 col-lg-6 col-xl-6">
                        <div class="form-group">
                            <label for="trip_country">Country</label>
                            <select class="form-control" id="trip_country" name="trip_country" required>
                                <option selected hidden>{{ current_trip.trip_country }}</option>
                                {% for country in countries %}
                                <option>{{ country }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                </div>

                <!-- Trip Description -->
                <div class="form-row">
                    <div class="col">
                        <div class="form-group">
                            <label for="trip_description">Trip Description</label>
                            <textarea class="form-control" name="trip_description" minlength="5" maxlength="200"
                                id="trip_description" cols="30" rows="10"
                                required>{{ current_trip.trip_description }}</textarea>
                        </div>
                    </div>
                </div>

                <!-- Trip Start and End Date -->
                <div class="form-row">
                    <div class="col">
                        <label for="trip_startdate">Start Date</label>
                        <input class="form-control" id="trip_startdate" name="trip_startdate" type="date"
                            value="{{ current_trip.trip_startdate.strftime('%Y-%m-%d') }}" required>
                    </div>

                    <div class="col">
                        <label for="trip_end_date">End Date</label>
                        <input class="form-control" id="trip_end_date" name="trip_end_date" type="date"
                            value="{{ current_trip.trip_end_date.strftime('%Y-%m-%d') }}" required>
                    </div>
                </div>

                <!-- Current Photos Preview -->
                <div class="form-row currentPhotos">
                    <div class="col">
                        <label for="editTripPrev">Current Photos</label>
                        {% if trip_path['resources']|length > 0 %}
                        <div id="editTripPrev" class="previewCurrentImages">
                            {% for res in trip_path['resources'] %}
                            <div class="imgPrevWrapper">
                                <a id="{{ res.asset_id }}" class="delEditImg" aria-label="Delete current photo">
                                        <img class="previewPictureEdit img-centered shakeEffect"
                                            src="{{ '%s.jpg' % img_url(res.folder, res.filename) }}" alt="{{ res.filename }}">
                                </a>
                            </div>

                            <!-- The delete photo confirmation modal -->
                            <div class="row no-gutters">
                                <div class="col-12">
                                    <div id="deletePhotoModal_{{ res.asset_id }}" class="modal deletePhotoModal">

                                        <!-- Modal content -->
                                        <div class="modal-content">
                                            <div class="row no-gutters">
                                                <div class="col-2 ml-auto">
                                                    <span class="close closeDeleteConfirm">&times;</span>
                                                </div>

                                                <!-- Confirmation message -->
                                                <div class="col-12">
                                                    <div class="row no-gutters">
                                                        <div class="col-12">
                                                            <h2 class="text-center">You are going to delete this
                                                                photo! Are you sure?</h2>
                                                        </div>
                                                    </div>
                                                    <hr>
                                                    <div class="row no-gutters content-alignment deleteBtnModal">
                                                        <div class="col-4 col-md-2 content-alignment">
                                                            <a class="btn btn-primary closeDeleteConfirm" aria-label="Close delete current photo confirmation">Cancel</a>
                                                        </div>
                                                        <div class="col-4 col-md-2 content-alignment">
                                                            <a class="btn btn-danger deletePhotoBtn closeDeleteConfirm"
                                                                data-flname="{{ res.filename }}"
                                                                data-trip="{{ current_trip._id }}"
                                                                data-img="{{ res.asset_id }}"
                                                                href="{{ url_for('delete_img.delete_img', trip_id=current_trip._id, filename=res.filename) }}" aria-label="Delete current photo confirm button">
                                                                Delete
                                                            </a>
                                                        </div>
                                                    </div>
                                                </div>

                                            </div>
                                        </div>

                                    </div>
                                </div>
                            </div>

                            {% endfor %}
                        </div>
                        {% else %}
                        <div id="editTripPrev" class="previewCurrentImages">
                            <h3 class="text-center">No photos to show</h3>
                        </div>
                        {% endif %}
                    </div>
                </div>

                <!-- Trip photos -->
                <div class="form-row">
                    <div class="col">
                        <div class="form-group">
                            <label for="trip_photos" class="form-label">Add New Photos</label>
                            <input class="form-control" type="file" id="trip_photos" name="trip_photos"
                                accept="image/jpg, image/jpeg, image/png" multiple />
                            <small>*15 pictures limit per trip</small>
                            <small> *The first picture will be used as post background</small>
                        </div>

                        <div id="newTripPrev" class="previewImages">
                        </div>
                    </div>
                </div>

                <!-- Trip Privacy -->
                <div class="form-row">
                    <div class="col">
                        <div class="form-group">
                            <label for="trip_privacy">Who Can See This Trip?</label>
                            <select class="form-control" id="trip_privacy" name="trip_privacy" required>
                                <option selected hidden>{{ current_trip.trip_privacy }}</option>
                                <option>Public</option>
                                <option>Private</option>
                            </select>
                        </div>
                    </div>
                </div>

                <hr>

                <!-- Submit/reset button add new trip form -->
                <div class="form-row edit_buttons">
                    <div class="col content-alignment">
                        <button type="submit" class="btn btn-primary tripFormBtn tripAddBtn updateTripBtn">Update
                            Trip</button>
                    </div>
                </div>

            </form>

        </div>
    </div>
</div>

{% endblock %}